[commands.golangci-lint-fmt]
type = "both"
cmd = ["golangci-lint", "fmt"]
lint-flags = "--diff"
ok-exit-codes = 0
invoke = "once"
include = ["**/*.go"]
exclude = ["testdata/MaxMind-DB/**"]

[commands.golangci-lint]
type = "both"
cmd = ["golangci-lint", "run"]
tidy-flags = ["--fix"]
ok-exit-codes = 0
expect-stderr = true
invoke = "once"
path-args = "dir"
include = ["**/*.go"]
exclude = ["testdata/MaxMind-DB/**"]

[commands.prettier-markdown]
type = "both"
include = [
    "**/*.md"
]
exclude = [
    "testdata/MaxMind-DB/**"
]
cmd = [
    "npx",
    "prettier",
    "--parser",
    "markdown",
    "--prose-wrap",
    "always",
]
lint-flags = "--check"
tidy-flags = "--write"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = ["Code style issues", "npm warn exec"]
